lidar_camera_calib:
    ros__parameters:
        # Data path. adjust them!
        image_file: "/home/simi/gv_ws/pitch_6/img.png"
        pcd_file: "/home/simi/gv_ws/pitch_6/map.pcd"
        result_file: "/home/simi/gv_ws/pitch_6/extrinsic.txt"

        # Camera Parameters. Adjust them!
        camera_matrix: [914.3226318359375, 0.0, 633.5563354492188, 
                        0.0, 914.1400756835938, 373.4688415527344,
                        0.0, 0.0, 1.0]
        dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

        # Calibration Parameters.!
        calib_config_file: "/home/simi/gv_ws/src/lidar_camera_calib/config/config_indoor.yaml"
        use_rough_calib: true # set true if your initial_extrinsic is bad
        save_img: true
        folder: "/home/simi/gv_ws/src/lidar_camera_calib/result"